import React, { useEffect, useState } from 'react';
import { SafeAreaView, View, Text, TextInput, Pressable, FlatList, StyleSheet, Linking } from 'react-native';
import * as Speech from 'expo-speech';

const API = process.env.EXPO_PUBLIC_API_URL || 'http://localhost:3000';
export default function App() {
  const [command, setCommand] = useState(''); const [messages, setMessages] = useState([{role:'assistant',text:'Hi! Tell me what to schedule.'}]); const [loading, setLoading] = useState(false);
  const send = async () => { if (!command.trim() || loading) return; const text=command.trim(); setCommand(''); setMessages(m=>[...m,{role:'user',text}]); setLoading(true); try { const r=await fetch(`${API}/api/command`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({command:text,sessionId:'mobile'})}); const d=await r.json(); if(r.status===401){setMessages(m=>[...m,{role:'assistant',text:'Connect Google Calendar in the web app first.'}]);return;} const answer=d.message||d.question||'Done.'; setMessages(m=>[...m,{role:'assistant',text:answer}]); Speech.speak(answer); } catch(e){setMessages(m=>[...m,{role:'assistant',text:'The assistant is unavailable. Check your API URL.'}]);} finally{setLoading(false)} };
  return <SafeAreaView style={styles.safe}><View style={styles.container}><Text style={styles.kicker}>ORBIT MOBILE</Text><Text style={styles.title}>Your calendar, anywhere.</Text><FlatList style={styles.list} data={messages} keyExtractor={(_,i)=>String(i)} renderItem={({item})=><View style={[styles.bubble,item.role==='user'?styles.user:styles.bot]}><Text style={styles.text}>{item.text}</Text></View>}/><TextInput value={command} onChangeText={setCommand} placeholder="Ask your calendar assistant…" placeholderTextColor="#8991ae" style={styles.input} multiline/><Pressable style={styles.button} onPress={send}><Text style={styles.buttonText}>{loading?'Thinking…':'Send command'}</Text></Pressable><Pressable onPress={()=>Linking.openURL(`${API}/auth/google`)}><Text style={styles.link}>Connect Google Calendar</Text></Pressable></View></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#0d1324'},container:{flex:1,padding:24},kicker:{color:'#96a5d4',letterSpacing:2,fontSize:11},title:{color:'#fff',fontSize:32,fontWeight:'800',marginVertical:18},list:{flex:1},bubble:{padding:14,borderRadius:16,marginVertical:6,maxWidth:'90%'},bot:{backgroundColor:'#25345c'},user:{backgroundColor:'#267358',alignSelf:'flex-end'},text:{color:'#fff',fontSize:15,lineHeight:22},input:{minHeight:80,borderRadius:14,backgroundColor:'#18233e',color:'#fff',padding:14,marginTop:15},button:{backgroundColor:'#708dff',padding:15,borderRadius:13,alignItems:'center',marginTop:10},buttonText:{color:'#fff',fontWeight:'700'},link:{color:'#aab9ff',textAlign:'center',padding:16}});
